### PR TITLE
[BAAAS-300] Use Managed Services dependency from Maven Central

### PR DESCRIPTION
**Pull request by robpblake**
This PR updates to use the Managed Services dependency from Maven Central instead of Github Packages. This allows us to reduce the permissions on our CI pipeline and also removes the need to provide a personal access token when building the Fleet Manager.

### CODE REVIEW

**Comment by robpblake** [comment]
@myeung18 Would you mind giving this a quick review please? This PR updates our dependency for the Managed Services JAR to get it from Maven Central rather than GitHub packages, which simplifies our CI and local build setup.

cheers,
Rob

**Review by myeung18 — COMMENTED** [review]
https://github.com/robpblake/baaas-decision-fleet-manager/blob/5fb29c35015f4ffb4f7bfc2b343ca94120656308/.gitlab-ci-settings.xml#L9

are we still using redhat-developer(Red Hat Developer GitHub Packages) in github in some case?

**Comment by robpblake** [comment]
> https://github.com/robpblake/baaas-decision-fleet-manager/blob/5fb29c35015f4ffb4f7bfc2b343ca94120656308/.gitlab-ci-settings.xml#L9
> 
> are we still using redhat-developer(Red Hat Developer GitHub Packages) in github in some case?

@myeung18 That is the CI definition file for when we were running our CI pipelines on GitLab. We no longer need that so it's not referenced on GitHub. I will have another PR shortly to delete all GitLab references as part of the final tidy up of the migration from GitLab to GitHub.

cheers,
Rob

**Comment by myeung18** [comment]
> > https://github.com/robpblake/baaas-decision-fleet-manager/blob/5fb29c35015f4ffb4f7bfc2b343ca94120656308/.gitlab-ci-settings.xml#L9
> > are we still using redhat-developer(Red Hat Developer GitHub Packages) in github in some case?
> 
> @myeung18 That is the CI definition file for when we were running our CI pipelines on GitLab. We no longer need that so it's not referenced on GitHub. I will have another PR shortly to delete all GitLab references as part of the final tidy up of the migration from GitLab to GitHub.
> 
> cheers,
> Rob


Anything else is looking good.
LGTM

**Pull request merged**
